FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        iproute2 iputils-ping net-tools \
        tcpdump iperf3 dnsutils \
        wget curl ca-certificates \
        python3 python3-pip \
        git make g++ libpcap-dev mgen\
    ; \
    rm -rf /var/lib/apt/lists/*