#!/bin/bash
export PATH=$PATH:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin

top_dir=$1
node=$2
env=$3
start_utc=$4

# source in an environment if provided
if [ -n "$env" ]
then
    . $env
fi

# run a local init if provided
if [ -f $top_dir/$node/init_biz.local ]
then
    bash $top_dir/$node/init_biz.local "$top_dir" "$node" "$start_utc" \
       2>&1 | tee  $top_dir/persist/$node/var/log/init_biz.log
fi
