#!/bin/bash
<%
import re
biz_addrs = {}
for node,items in __share.items():
    for key, value in items.items():
        m = re.match(r'biz_addr',key)
        if m:
           biz_addrs[node] = value

nodes_str = " ".join(biz_addrs.keys())
%>

# map node -> biz IP for shell use
declare -A biz_addrs=(
% for node, addr in biz_addrs.items():
  ['${node}']="${addr}"
% endfor
)

start_links() {
  for i in ${'"${!biz_addrs[@]}"'}; do
    biz="$i-biz"
    emu="$i-emane"

    pid_biz=$(docker inspect -f '{{.State.Pid}}' "$biz")
    pid_emu=$(docker inspect -f '{{.State.Pid}}' "$emu")

    ip link add veth-$i-biz type veth peer name veth-$i-emane

    ip link set veth-$i-biz  netns "$pid_biz"
    ip link set veth-$i-emane netns "$pid_emu"

    nsenter -t "$pid_biz" -n ip addr add ${'${biz_addrs[$i]}'} dev veth-$i-biz
    nsenter -t "$pid_biz" -n ip link set veth-$i-biz up

    # not necessary to set IP for emane side
    nsenter -t "$pid_emu" -n ip link set veth-$i-emane name emane0
    nsenter -t "$pid_emu" -n ip link set emane0 up
  done
}

stop_links() {
  for i in ${'"${!biz_addrs[@]}"'}; do
    biz="$i-biz"
    emu="$i-emane"

    pid_biz=$(docker inspect -f '{{.State.Pid}}' "$biz") || true
    # veth deletion from one side is sufficient
    if [ -n ${'"${pid_biz:-}"'} ]; then
      nsenter -t "$pid_biz" -n ip link del veth-biz$i 2>/dev/null || true
    fi
  done
}

case ${'"${1:-}"'} in
  start)
    start_links
    ;;
  stop)
    stop_links
    ;;
  *)
    echo "usage: $0 {start|prep|stop}" >&2
    exit 1
    ;;
esac
